"""add assigned column to db

Revision ID: 15e745aa1abc
Revises: cf24bad13121
Create Date: 2019-05-21 19:05:51.976397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e745aa1abc'
down_revision = 'cf24bad13121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('assigned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'assigned')
    # ### end Alembic commands ###
