"""add functionality to Assignment model

Revision ID: 191367f5b6b1
Revises: 0e97de0946c2
Create Date: 2019-05-23 12:40:50.459129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191367f5b6b1'
down_revision = '0e97de0946c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('phone_number', sa.Text(), nullable=True))
    op.add_column('assignment', sa.Column('response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'response')
    op.drop_column('assignment', 'phone_number')
    # ### end Alembic commands ###
