"""empty message

Revision ID: 2a21a23a1be0
Revises: e210385ed4cf
Create Date: 2019-08-05 17:31:03.228210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a21a23a1be0'
down_revision = 'e210385ed4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('skips', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'skips')
    # ### end Alembic commands ###
