"""add CleanupHour model

Revision ID: cf24bad13121
Revises: 96040dd130ff
Create Date: 2019-05-21 01:00:54.851312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf24bad13121'
down_revision = '96040dd130ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanup_hour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Text(), nullable=True),
    sa.Column('due_time', sa.Text(), nullable=True),
    sa.Column('worth', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cleanup_hour')
    # ### end Alembic commands ###
