"""add Submission model

Revision ID: e210385ed4cf
Revises: 48372b7e85ab
Create Date: 2019-06-05 17:30:38.706681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e210385ed4cf'
down_revision = '48372b7e85ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dir_name', sa.String(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_assignment_id'), 'submission', ['assignment_id'], unique=True)
    op.create_index(op.f('ix_submission_dir_name'), 'submission', ['dir_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_dir_name'), table_name='submission')
    op.drop_index(op.f('ix_submission_assignment_id'), table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
